# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.FileField(blank=True, upload_to=questions.models.cover_upload_path)),
                ('color', models.CharField(choices=[('Red', '#F44336'), ('Orange', '#FF9800'), ('Yellow', '#FFEB3B'), ('Green', '#4CAF50'), ('Blue', '#2196F3'), ('Indigo', '#3F51B5'), ('Violet', '#9C27B0'), ('Pink', '#E91E63'), ('Brown', '#795548'), ('Grey', '#9E9E9E'), ('Black', '#000000'), ('White', '#FFFFFF')], default='White', max_length=10)),
            ],
        ),
    ]
